# Generated by Django 5.1.3 on 2024-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_date_from',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_date_to',
            field=models.DateField(default='2024-01-02'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_duration',
            field=models.CharField(default='1 hour', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_instructor',
            field=models.CharField(default='Default Instructor', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_location',
            field=models.CharField(default='Default Location', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_time_from',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_time_to',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_title',
            field=models.CharField(default='Default Service Title', max_length=100),
        ),
    ]
