# Generated by Django 5.1.3 on 2024-12-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
