# Generated by Django 5.1.3 on 2025-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('timing', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('closes_on', models.CharField(help_text="Closes on format (e.g., '2nd jan')", max_length=50)),
            ],
        ),
    ]
