# Generated by Django 5.1.3 on 2025-01-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
