# Generated by Django 5.1.3 on 2025-01-02 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timing',
        ),
        migrations.AddField(
            model_name='event',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Online', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='mode_of_service',
            field=models.CharField(default='Online', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='time_from',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='time_to',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='60 mins', max_length=100),
        ),
    ]
