# Generated by Django 5.1.3 on 2024-12-03 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.AddField(
            model_name='service',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='service',
            name='instructor',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='Online', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='time_from',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='service',
            name='time_to',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='service',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(default='60 mins', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mode_of_service',
            field=models.CharField(default='Online', max_length=100),
        ),
    ]
